name: Week 3 Activity

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  assignment:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: 18

      - name: OS package dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Display self-description
        run: echo "This is Week 3's in-class assignment!"
      - name: Runs all tests
        run: npm run test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: Code coverage report
          path: output/test/code-coverage.html